name: ensemble
method: bayes
metric:
  goal: minimize
  name: valid_best/loss
parameters:
  model_name:
    value: ensemble
  model_class:
    value: Ensemble
  epochs:
    value: 5
  num_classes:
    value: 10
  input_size:
    value: [3, 32, 32]
  activation:
    value: ReLU
  batch_size:
    value: 1024
  model:
    value:
      - name: fc
        in_features: 18
        out_features: 10
        add_activation: false
  learning_rate:
    distribution: log_uniform_values
    min: 0.0001
    max: 0.1
  beta1:
    distribution: log_uniform_values
    min: 0.7
    max: 0.99999
  beta2:
    distribution: log_uniform_values
    min: 0.9
    max: 0.999999
  l2_penalty:
    distribution: uniform
    min: 0
    max: 0.3
  dropout:
    value: 0.4
  batch_norm:
    value: true
  optimizer:
    value: Adam
  random_crop_add:
    value: false
  random_crop_scale:
    value: 0.2
  random_crop_ratio:
    value: 0.2
  random_flip_add:
    value: false
  random_flip_prob:
    value: 0.5
  random_rotation_add:
    value: false
  random_rotation_degrees:
    value: 30
  random_color_jitter_add:
    value: false
  random_gaussian_blur_add:
    value: false
  cutmix_add:
    value: none
