name: resnet_cnn
method: random
metric:
  goal: minimize
  name: valid/loss
parameters:
  model_name:
    value: resnet_cnn
  epochs:
    value: 60
  num_classes:
    value: 10
  input_size:
    value: [3, 32, 32]
  activation:
    value: ReLU
  batch_size:
    value: 1024
  model:
    value:
      - name: conv
        in_channels: 3
        out_channels: 16
        kernel_size: 3
        stride: 1
        padding: 1
      - name: dropout
      - name: res_block
        main_path_model:
          - name: conv
            in_channels: 16
            out_channels: 16
            kernel_size: 3
            stride: 1
            padding: 1
          - name: dropout
          - name: conv
            in_channels: 16
            out_channels: 16
            kernel_size: 3
            stride: 1
            padding: 1
            add_activation: false
            add_batch_norm: false
        shortcut_path_model: []
      - name: dropout
      - name: res_block
        main_path_model:
          - name: conv
            in_channels: 16
            out_channels: 32
            kernel_size: 3
            stride: 2
            padding: 1
          - name: dropout
          - name: conv
            in_channels: 32
            out_channels: 32
            kernel_size: 3
            stride: 1
            padding: 1
            add_activation: false
            add_batch_norm: false
        shortcut_path_model:
          - name: conv
            in_channels: 16
            out_channels: 32
            kernel_size: 1
            stride: 2
            padding: 0
            add_activation: false
            add_batch_norm: false
      - name: dropout
      - name: res_block
        main_path_model:
          - name: conv
            in_channels: 32
            out_channels: 64
            kernel_size: 3
            stride: 2
            padding: 1
          - name: dropout
          - name: conv
            in_channels: 64
            out_channels: 64
            kernel_size: 3
            stride: 1
            padding: 1
            add_activation: false
            add_batch_norm: false
        shortcut_path_model:
          - name: conv
            in_channels: 32
            out_channels: 64
            kernel_size: 1
            stride: 2
            padding: 0
            add_activation: false
            add_batch_norm: false
        add_batch_norm: false
      - name: avg_pool
        kernel_size: 1
      - name: flatten
      - name: fc
        in_features: 4096
        out_features: 10
        add_activation: false
  learning_rate:
    distribution: log_uniform_values
    min: 0.0001
    max: 0.1
  beta1:
    distribution: log_uniform_values
    min: 0.7
    max: 0.99999
  beta2:
    distribution: log_uniform_values
    min: 0.9
    max: 0.999999
  l2_penalty:
    values: [ 0.0, 0.01, 0.05, 0.1, 0.15, 0.25, 0.3 ]
  dropout:
    values: [ 0, 0.1, 0.2, 0.3, 0.4, 0.5 ]
  batch_norm:
    values: [ false, true ]
  optimizer:
    values: [ Adam, SGD ]
  random_crop_add:
    values: [ false, true ]
  random_crop_scale:
    distribution: uniform
    min: 0.05
    max: 1.0
  random_crop_ratio:
    distribution: uniform
    min: 0.0
    max: 0.8
  random_flip_add:
    values: [ false, true ]
  random_flip_prob:
    distribution: uniform
    min: 0.0
    max: 1.0
  random_rotation_add:
    values: [ false, true ]
  random_rotation_degrees:
    distribution: q_uniform
    q: 1
    min: 0
    max: 180
  random_color_jitter_add:
    values: [ false, true ]
  random_color_jitter_brightness:
    distribution: uniform
    min: 0
    max: 1
  random_color_jitter_contrast:
    distribution: uniform
    min: 0
    max: 1
  random_color_jitter_saturation:
    distribution: uniform
    min: 0
    max: 1
  random_color_jitter_hue:
    distribution: uniform
    min: 0
    max: 0.5
  random_gaussian_blur_add:
    values: [ false, true ]
  random_gaussian_blur_kernel_size:
    values: [ 3, 5, 7 ]
  random_gaussian_blur_sigma:
    distribution: uniform
    min: 0.1
    max: 1
  cutmix_add:
    values: [ none, cut, mix ]
early_terminate:
  type: hyperband
  s: 2
  eta: 3
  max_iter: 60