name: resnet50_pretrained
method: random
metric:
  goal: minimize
  name: valid/loss_epoch
parameters:
  model_name:
    value: resnet50_pretrained
  epochs:
    value: 10
  num_classes:
    value: 10
  input_size:
    value: [3, 32, 32]
  activation:
    value: ReLU
  batch_size:
    value: 1024
  model:
    value:
      - name: resnet50
  learning_rate:
    distribution: log_uniform_values
    min: 0.0001
    max: 0.1
  dropout:
    values: [0, 0.1, 0.2, 0.3, 0.5]
  batch_norm:
    values: [false, true]
  optimizer:
    values: [Adam, SGD]
  random_crop_add:
    values: [false, true]
  random_crop_scale:
    distribution: uniform
    min: 0.05
    max: 1.0
  random_crop_ratio:
    distribution: uniform
    min: 0.0
    max: 0.8
  random_flip_add:
    values: [false, true]
  random_flip_prob:
    distribution: uniform
    min: 0.0
    max: 1.0
  random_rotation_add:
    values: [false, true]
  random_rotation_degrees:
    distribution: q_uniform
    q: 1
    min: 0
    max: 180
  random_color_jitter_add:
    values: [false, true]
  random_color_jitter_brightness:
    distribution: uniform
    min: 0
    max: 1
  random_color_jitter_contrast:
    distribution: uniform
    min: 0
    max: 1
  random_color_jitter_saturation:
    distribution: uniform
    min: 0
    max: 1
  random_color_jitter_hue:
    distribution: uniform
    min: 0
    max: 0.5
  random_gaussian_blur_add:
    values: [false, true]
  random_gaussian_blur_kernel_size:
    values: [3, 5, 7]
  random_gaussian_blur_sigma:
    distribution: uniform
    min: 0.1
    max: 1
early_terminate:
  type: hyperband
  s: 2
  eta: 3
  max_iter: 10