name: simple_cnn
method: random
metric:
  goal: minimize
  name: valid/loss_epoch
parameters:
  model_name:
    value: simple_cnn
  epochs:
    value: 5
  num_classes:
    value: 10
  input_size:
    value: [3, 32, 32]
  activation:
    value: ReLU
  loss_function:
    value: nll_loss
  batch_size:
    value: 1024
  model:
    value:
      - name: conv
        in_channels: 3
        out_channels: 16
        kernel_size: 3
        stride: 1
        padding: 1
      - name: dropout
      - name: max_pool
        kernel_size: 2
      - name: conv
        in_channels: 16
        out_channels: 32
        kernel_size: 3
        stride: 1
        padding: 1
      - name: dropout
      - name: max_pool
        kernel_size: 2
      - name: conv
        in_channels: 32
        out_channels: 64
        kernel_size: 3
        stride: 1
        padding: 1
      - name: dropout
      - name: max_pool
        kernel_size: 2
      - name: flatten
      - name: fc
        in_features: 1024
        out_features: 64
      - name: fc
        in_features: 64
        out_features: 10
        add_activation: false
  learning_rate:
    value: 0.01
  dropout:
    value: 0
  batch_norm:
    value: false
  optimizer:
    value: Adam
  random_crop_add:
    value: false
  random_crop_scale:
    distribution: uniform
    min: 0.05
    max: 1.0
  random_crop_ratio:
    distribution: uniform
    min: 0.0
    max: 0.8
  random_flip_add:
    value: false
  random_flip_prob:
    distribution: uniform
    min: 0.0
    max: 1.0
  random_rotation_add:
    value: false
  random_rotation_degrees:
    distribution: q_uniform
    q: 1
    min: 0
    max: 180
  random_color_jitter_add:
    value: false
  random_color_jitter_brightness:
    distribution: uniform
    min: 0
    max: 1
  random_color_jitter_contrast:
    distribution: uniform
    min: 0
    max: 1
  random_color_jitter_saturation:
    distribution: uniform
    min: 0
    max: 1
  random_color_jitter_hue:
    distribution: uniform
    min: 0
    max: 0.5
  random_gaussian_blur_add:
    value: false
  random_gaussian_blur_kernel_size:
    values: [3, 5, 7]
  random_gaussian_blur_sigma:
    distribution: uniform
    min: 0.1
    max: 1
